### PR TITLE
Initial slide fixes for ICCS summer school 24

### PR DESCRIPTION
**Pull request by ma595**
This PR fixes minimal aspects of the workshop's accompanying slides in readiness for the 2024 edition of the ICCS summer school. There is scope to add more.

I have added Surbhi and I as additional authors. I would like to emphasise that we are teaching the session, if possible. @jatkinson1000 do you you have any formatting suggestions?

- [x] Fix the parameter update rule. See https://en.wikipedia.org/wiki/Stochastic_gradient_descent
- [x] Various spelling and style changes
- [x] Modify names of presenters, and acknowledge Jim and Jack. 
- [x] Create 'material' slide that points to github link and cites Jack and Jim's code and JOSE paper.
- [x] Amend contact with two additional columns. 

Closes part of #61

### CODE REVIEW

**Review by jatkinson1000 — COMMENTED** [review]
All seem sensible.

One comment is to drop the 'AZ' from @jdenholm's affiliation and make him UoC or something, as I know they are picky about what their name appears on.

**Comment by ma595** [comment]
Any suggestions on how to make the actual speakers' names stand out on the title page? i.e. with some quarto emphasis effect? I wasn't able to figure that out quickly.

**Review by jatkinson1000 — APPROVED** [review]
All good from me.

Regarding the formatting question - my suggestion would be to put yourself and Surbhi on the title slide to make it clear who is teaching.

What you could do is put a note on the subsequent slide with license and repo links etc to say it is based on the workshop developed by Jim and I. If you could also add a citation to the JOSE paper there that would be wonderful.

I will approve the PR now, as this is not a critical blocker, but that change would be appreciated :)

**Review by surbhigoel77 — APPROVED** [review]
LGTM

**Comment by ma595** [comment]
> LGTM

I'll attempt to address Jack's comments first.

**Pull request merged**
